name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify course

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout the LibreLingo tools
      uses: actions/checkout@v2
      with:
        repository: 'szabgab/LibreLingo-tools'
        path: LibreLingo-tools

    - name: Checkout the LibreLingo
      uses: actions/checkout@v2
      with:
        repository: 'kantord/LibreLingo'
        path: LibreLingo


    - name: Install dependencies
      run: |
          python -V
          pip install -r LibreLingo-tools/requirements.txt

    - name: Check course
      run: |
          python LibreLingo-tools/lili.py --ids --course course/ --images LibreLingo/apps/web/static/images/
